### ISSUE TITLE
Messed up graphics with newer versions of Brackets

### ISSUE THREAD

**Issue by Daankovski** [dnbard/brackets-documents-toolbar#46] opened 2015-01-05 21:51 UTC
There is a big white bar where everything is in, and the toolbar isn't the shape it is supposed to be. It basically are black squares now.

This is your latest release(5.5 or something) with the latest version of Brackets.

![preview](https://cloud.githubusercontent.com/assets/9716918/5620550/39752060-952d-11e4-8509-348ffeb96f79.png)

**Comment by dnbard** [comment] 2015-01-06 08:53
I cannot reproduce this on my local PC.
* Try to remove extension completely and install new version (there was an issue similar to yours, but it was fixed in last release)
* If issue still in place then there is a conflict with another installed extension

**Comment by arjunrp** [comment] 2015-01-07 17:01
Got the same issue in windows and Ubuntu, in ubuntu. Removed the extension manually and copied the source code from this repo, still the issue exist !!

**Comment by dnbard** [comment] 2015-01-07 17:05
I don't have Linux installation. I'll gladly approve pull request if you manage to solve this issue.

**Comment by arjunrp** [comment] 2015-01-07 17:08
Upon checking the developer tools, i was able to find a bunch of issues.
'brackets-documents' is the directory name of extension
Hope this helps !!


![screenshot from 2015-01-07 22 33 43](https://cloud.githubusercontent.com/assets/6293595/5649646/810f301e-96bd-11e4-9628-17dfc7ee5441.png)
![screenshot from 2015-01-07 22 33 59](https://cloud.githubusercontent.com/assets/6293595/5649658/9b48caf8-96bd-11e4-959d-f9f7797e8eed.png)
![screenshot from 2015-01-07 22 34 10](https://cloud.githubusercontent.com/assets/6293595/5649664/a1356a66-96bd-11e4-8c47-97c106d80de8.png)

**Comment by dnbard** [comment] 2015-01-08 09:34
I doubt that this issue is related to this deprecated events (guh, why are they keep changing their API ?? :grin: ) Will fix them when I have time for it.

**Comment by Daankovski** [comment] 2015-01-09 13:53
Hey man, I deleted all my plugins and installed yours as the only one, but still the issue remains.

**Comment by arjunrp** [comment] 2015-01-09 14:49
Hi, I was just able to rectify this problem, however what i have done cannot be added to to the main repository because it is just a hack, and may not support on all themes of brackets(i hope you are using 'Brackets Dark'). 
Add the css rule 'background-color:#343739;' for the element '.ext-documents' to the file 
extensions folder\user\dnbard.documents-toolbar\styles\main.css .
Then reopen brackets, the issue will be solved !! :blush:

**Comment by dnbard** [comment] 2015-01-09 14:55
What kind of theme are you using? Dark or light?
I'm asking because this fix was applied once.

**Comment by Daankovski** [comment] 2015-01-09 15:21
At the moment, I'm using the Dreamweaver theme, but at the time of deleting all my extensions none were used

**Comment by dnbard** [comment] 2015-01-09 15:27
@arjunrp @Daankovski guys this extension already have a [rule to color main bar to dark color for dark themes](https://github.com/dnbard/brackets-documents-toolbar/blob/master/styles/main.css#L134) it use `dark` class from `body` tag (that is set by Brackets). Please look in Development Tools on `body` tag and write here classes it have.

**Comment by arjunrp** [comment] 2015-01-09 16:18
@dnbard , I was not able to find dark class or any theme related class in body, Upon further inspection, i found that the theme is applied to content below the document toolbar.
So the theme will be set to the editing area only.

**Comment by dnbard** [comment] 2015-01-09 16:53
@arjunrp Could you show me how theme name is set on Linux so I can implement checker for different OS ?

**Comment by arjunrp** [comment] 2015-01-09 17:02
@dnbard , Sorry i didn't understand. You want the theme name set in editing area??

**Comment by dnbard** [comment] 2015-01-09 17:51
@arjunrp Is your theme "dark" one? Do you have this "dark" class at body tag on Linux? ![ ](http://content.screencast.com/users/dnbard/folders/Jing/media/71ebb96d-3f79-453b-af34-db67620821b3/2015-01-09_1948.png)

**Comment by arjunrp** [comment] 2015-01-09 18:23
@dnbard , Version 0.5.5 is working fine for default themes in bracket on both windows and ubuntu.
The problem is when we install extra themes, when these extra themes are used the 'dark' class is not added to body

This issue exist in windows and ubuntu, You can check this by installing packages like 'Themes' or 'Themes for Bracket' and select any theme other than inbuilt themes of Bracket.

![untitled](https://cloud.githubusercontent.com/assets/6293595/5684818/4061dec4-985a-11e4-8659-e68324646cba.png)

**Comment by dnbard** [comment] 2015-01-12 10:57
@Daankovski @arjunrp  Please test code from this repository. Is this issue resolved now?

**Comment by Daankovski** [comment] 2015-01-13 10:59
@dnbard well, the white bar is fixed,but the tabs are still messed up...
![screenshot_1](https://cloud.githubusercontent.com/assets/9716918/5719754/ab0d4024-9b1b-11e4-9829-ebba5ed1bd28.png)

**Comment by dnbard** [comment] 2015-01-13 12:18
And whats wrong with the tabs?

**Comment by Daankovski** [comment] 2015-01-15 20:02
@dnbard Well, they are not like this.

![screenshot_1](https://cloud.githubusercontent.com/assets/9716918/5765426/cc9f6426-9cf9-11e4-81b4-fe7f19a4b3f2.png)

**Comment by dnbard** [comment] 2015-01-15 20:05
@Daankovski  tabs now clone style from working files panel and not rely to own style for file names and icons. If you want icons then you need to install appropriate extension. There is some extensions that have exactly same icon set.

**Comment by Daankovski** [comment] 2015-01-15 20:08
@dnbard Yes, I know that and I already had thos icons, but what I meant was that the tabs in my Brackets are squares and yours have a edge cut of, if you know what I mean.

**Comment by dnbard** [comment] 2015-01-16 09:12
@Daankovski  this was changed in one of recent releases at #35

**Closed** 2015-01-21 16:06 UTC
Labels: help wanted
